### ISSUE TITLE
Server.js - Application crashes when no profile picture

### ISSUE THREAD

**Issue by wolfe60629** [wolfe60629/GreenCheck-LMS#17]
When profile picture is null the application will crash. See bug log below: 

Database Query - VerifyUser
C:\Users\Home PC\Documents\GitHub\GreenCheck-LMS\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
    at Function.from (buffer.js:333:9)
    at new Buffer (buffer.js:289:17)
    at Query.<anonymous> (C:\Users\Home PC\Documents\GitHub\GreenCheck-LMS\functions.js:40:26)
    at Query.emit (events.js:315:20)
    at Query.RowDataPacket (C:\Users\Home PC\Documents\GitHub\GreenCheck-LMS\node_modules\mysql\lib\protocol\sequences\Query.js:158:10)
    at Protocol._parsePacket (C:\Users\Home PC\Documents\GitHub\GreenCheck-LMS\node_modules\mysql\lib\protocol\Protocol.js:260:14)
    at Parser._parsePacket (C:\Users\Home PC\Documents\GitHub\GreenCheck-LMS\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Home PC\Documents\GitHub\GreenCheck-LMS\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Home PC\Documents\GitHub\GreenCheck-LMS\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Home PC\Documents\GitHub\GreenCheck-LMS\node_modules\mysql\lib\Connection.js:88:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by wolfe60629** [comment]
This bug was caused by a null buffer that was never initialized as a string during the conversion over to base64. To fix the issue, we are now checking to see if the database returns a null value for the profile picture. If it is null, we are setting the profile picture to being an empty string.

            //Change Profile Picture To Base64
            if (profilePicture == null) { 
              profilePicture = "";
            }
              let buff = new Buffer(profilePicture);
              profilePicture = buff.toString('base64');
